export const products = [
  {
    "slug": "fancy",
    "title": "Fancy",
    "tagline": "Photobook elegan untuk menyimpan momen paling berharga",
    "specifications": "[\"40 foto\", \"24 halaman\", \"Hardcover\", \"Ukuran 15x21\", \"Kertas premium white pearl 150gr\"]",
    "highlight": "Cerita Manis dalam Genggaman",
    "highlight_description": "Momen bahagia kamu terlalu berharga kalau cuma numpuk di galeri HP. Fancy Photobook hadir dengan ukuran elegan 15x21 dan hardcover yang kokoh, bikin setiap halaman terasa spesial. Cocok buat kisah cinta, liburan, atau momen keluarga yang ingin terus dikenang. Dibuka kapan pun, rasanya selalu hangat ?",
    "feature": "Kenangan Terbaik Layak Dicetak Indah",
    "feature_description": "Momen bahagia itu sayang kalau cuma tersimpan di HP dan jarang dibuka. Fancy Photobook hadir dengan tampilan elegan dan hardcover kokoh, bikin setiap foto terasa lebih hidup dan berkesan.\nCocok untuk kisah cinta, momen keluarga, atau perjalanan spesial yang ingin selalu kamu kenang. Sekali dicetak, kenangannya bisa kamu rasakan berulang kali ✨",
    "price": 275000,
    "discount_amount": 20000,
    "final_price": 255000,
    "price_promo_double": 550000,
    "final_price_promo_double": 425000,
    "image_main_url": "https://ik.imagekit.io/lovisha/assets/fancy_3.jpg?updatedAt=1770384941325",
    "image_secondary_url": "https://ik.imagekit.io/lovisha/assets/fancy_2.jpg?updatedAt=1770384941325",
    "image_tertiary_url": "https://ik.imagekit.io/lovisha/assets/fancy_1.jpg?updatedAt=1770384942947",
    "is_promo": 1,
    "is_active": 1,
    "product_images": [
        "https://ik.imagekit.io/kidodia/assets/fancy/1.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/fancy/2.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/fancy/3.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/fancy/4.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/fancy/5.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/fancy/6.jpg?updatedAt=1772238467904",

    ]
  },
  {
    "slug": "snapbook",
    "title": "Snapbook",
    "tagline": "Ukuran ringkas, cerita tetap lengkap",
    "specifications": "[\"30 foto\", \"32 halaman\", \"Hardcover\", \"Ukuran 15x15\", \"Kertas premium white pearl 150gr\"]",
    "highlight": "Kecil, Hangat, Penuh Cerita",
    "highlight_description": "Jangan remehkan ukurannya ? Snapbook dirancang untuk momen-momen sederhana tapi bermakna. Dengan halaman yang lebih banyak, kamu bisa bercerita lebih panjang—dari senyum kecil sampai tawa lepas. Pas banget buat hadiah manis atau koleksi kenangan pribadi yang pengen sering dibuka.",
    "feature": "Kecil Ukurannya, Besar Ceritanya",
    "feature_description": "Nggak semua kenangan harus besar, tapi semuanya pantas dikenang. Snapbook Photobook dirancang ringkas dan nyaman digenggam, dengan halaman yang cukup untuk bercerita panjang.\nIdeal untuk hadiah manis, anniversary, atau koleksi pribadi yang pengen sering kamu buka. Karena kenangan terbaik itu yang dekat dan mudah dinikmati ?",
    "price": 249000,
    "discount_amount": 30000,
    "final_price": 219000,
    "price_promo_double": 438000,
    "final_price_promo_double": 287000,
    "image_main_url": "https://ik.imagekit.io/lovisha/assets/snapbook.jpg?updatedAt=1770384943025",
    "image_secondary_url": "https://ik.imagekit.io/lovisha/assets/snapbook_2.jpg?updatedAt=1770384943025",
    "image_tertiary_url": "https://ik.imagekit.io/lovisha/assets/snapbook_3.jpg?updatedAt=1770384943025",
    "is_promo": 0,
    "is_active": 1,
    "product_images": [
        "https://ik.imagekit.io/kidodia/assets/snapbook/1.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/snapbook/2.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/snapbook/3.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/snapbook/4.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/snapbook/5.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/snapbook/6.jpg?updatedAt=1772238467904",
    ]
  },
  {
    "slug": "large",
    "title": "Large",
    "tagline": "Lebih banyak foto, lebih luas bercerita",
    "specifications": "[\"40 foto\", \"32 halaman\", \"Hardcover\", \"Ukuran 15x15\", \"Kertas premium white pearl 150gr\"]",
    "highlight": "Ruang Lebih untuk Kenangan Besar",
    "highlight_description": "Kalau kenangan kamu banyak dan sayang kalau dipilih-pilih, Large Photobook jawabannya. Lebih lega, lebih puas, dan lebih hidup di setiap halaman. Ideal buat dokumentasi perjalanan, tumbuh kembang anak, atau momen spesial yang ingin dikenang dengan detail. Karena cerita besar butuh ruang yang layak ✨",
    "feature": "Lebih Luas, Lebih Puas Menyimpan Kenangan",
    "feature_description": "Kalau momen bahagiamu banyak dan semuanya penting, Large Photobook adalah pilihan tepat. Dengan halaman yang lebih lega, setiap foto bisa tampil maksimal tanpa terasa sempit.\nSempurna untuk dokumentasi liburan, perjalanan hidup, atau cerita keluarga yang ingin disimpan rapi dan indah. Karena kenangan besar layak tempat yang spesial ?",
    "price": 425000,
    "discount_amount": 30000,
    "final_price": 395000,
    "price_promo_double": 990000,
    "final_price_promo_double": 720000,
    "image_main_url": "https://ik.imagekit.io/lovisha/assets/large_1.jpg?updatedAt=1770384975037",
    "image_secondary_url": "https://ik.imagekit.io/lovisha/assets/large_2.jpg?updatedAt=1770384975037",
    "image_tertiary_url": "https://ik.imagekit.io/lovisha/assets/large_3.jpg?updatedAt=1770384975037",
    "is_promo": 1,
    "is_active": 1,
    "product_images": [
        "https://ik.imagekit.io/kidodia/assets/large/1.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/large/2.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/large/3.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/large/4.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/large/5.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/large/6.jpg?updatedAt=1772238467904",
    ]
  },
  {
    "slug": "softbook",
    "title": "Softbook",
    "tagline": "Simpel, hangat, dan selalu bikin rindu saat dibuka",
    "specifications": "[\"24 foto\", \"32 halaman\", \"Hardcover\", \"Ukuran 15x15\", \"Kertas premium white pearl 150gr\"]",
    "highlight": "Simpel, Hangat, dan Selalu Dekat",
    "highlight_description": "Buat kamu yang suka gaya simpel tapi tetap berkesan. Softbook Photobook menyimpan momen-momen favorit dengan rapi dan nyaman dibuka kapan saja. Cocok untuk daily memories, anniversary, atau hadiah kecil penuh makna. Karena kenangan indah nggak harus ribet ?",
    "feature": "Simpel Tapi Penuh Makna",
    "feature_description": "Buat kamu yang suka gaya sederhana tapi tetap bermakna, Softbook Photobook jadi pilihan yang pas. Ringkas, nyaman dibuka, dan cocok untuk menyimpan momen sehari-hari yang berharga.\nEntah itu cerita kecil, kenangan personal, atau hadiah penuh perhatian—semuanya terasa lebih nyata saat dicetak ?",
    "price": 275000,
    "discount_amount": 27500,
    "final_price": 247500,
    "price_promo_double": 550000,
    "final_price_promo_double": 405000,
    "image_main_url": "https://ik.imagekit.io/lovisha/assets/softbook_1.jpg",
    "image_secondary_url": "https://ik.imagekit.io/lovisha/assets/softbook_2.jpg?updatedAt=1770384944042",
    "image_tertiary_url": "https://ik.imagekit.io/lovisha/assets/snapbook_3.jpg?updatedAt=1770384942963",
    "is_promo": 0,
    "is_active": 1,
    "product_images": [
        "https://ik.imagekit.io/kidodia/assets/softbook/1.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/softbook/2.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/softbook/3.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/softbook/4.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/softbook/5.jpg?updatedAt=1772238467904",
        "https://ik.imagekit.io/kidodia/assets/softbook/6.jpg?updatedAt=1772238467904",
    ]
  }
]